spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:none}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: ${JPA_HIBERNATE_DDL_AUTO:none}
        default_batch_fetch_size: 1000
  jwt:
    secret: ${JWT_SECRET}
    access-token-validity-in-seconds: 2592000
    refresh-token-validity-in-seconds: 2592000
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
      database: ${REDIS_DATABASE:0}
